Kinto/kinto-attachment

.travis.yml
README.rst
kinto_attachment/tests/__init__.py
kinto_attachment/tests/config/local.ini
kinto_attachment/tests/config/s3.ini
kinto_attachment/tests/test_views_attachment.py
kinto_attachment/views.py
setup.py
tox.ini

Basic wire-up

---

README.rst
demo/README.rst
demo/index.html
demo/script.js
kinto_attachment/tests/__init__.py
kinto_attachment/tests/test_views_attachment.py
kinto_attachment/views.py

Add demo to post files from browser

---

README.rst
kinto_attachment/__init__.py
kinto_attachment/tests/__init__.py
kinto_attachment/tests/config/local.ini
kinto_attachment/tests/test_views_attachment.py
kinto_attachment/views.py

Validate schema and remove attachments on delete

---

README.rst
kinto_attachment/tests/test_views_attachment.py
kinto_attachment/views.py
tox.ini

Check permissions upload (fixes #9)

---

kinto_attachment/tests/test_views_attachment.py
kinto_attachment/views.py

Add delete endpoint (fixes #15)

---

.gitignore
.travis.yml
Makefile
README.rst

Add a Makefile to install and run tests.

---

README.rst
kinto_attachment/tests/__init__.py
kinto_attachment/tests/config/s3.ini
kinto_attachment/tests/test_views_attachment.py
kinto_attachment/views.py

Obfuscate public locations of files (fixes #14)

---

CHANGELOG.rst
README.rst
setup.py

Preparing release 0.1.0

---

CHANGELOG.rst
README.rst
kinto_attachment/tests/config/local.ini
kinto_attachment/tests/config/s3.ini
kinto_attachment/tests/test_views_attachment.py
kinto_attachment/views.py

Setting to store files into folders by bucket or collection (fixes #22)

---

kinto_attachment/tests/__init__.py
kinto_attachment/tests/config/events.ini
kinto_attachment/tests/test_events.py

Make sure ResourceChanged is triggered on file upload (fixes #29)

---

CHANGELOG.rst
kinto_attachment/tests/test_views_attachment.py
kinto_attachment/views.py

Remove existing file when attachment is replaced (fixes #28)

---

.travis.yml
tox.ini

Add Travis job for Kinto master

---

.travis.yml
README.rst
scripts/download.py
scripts/upload.py
tox.ini

Needs: https://github.com/Kinto/kinto.py/pull/59

Upload script ported to cli utils

---

README.rst
kinto_attachment/tests/config/local.ini
kinto_attachment/tests/test_views_attachment.py

Enable the default bucket in tests

---

.travis.yml
README.rst
kinto_attachment/tests/__init__.py
kinto_attachment/tests/test_views_attachment.py
kinto_attachment/views.py
tox.ini

Port to Python3 (fixes #43)

---

README.rst

@Natim we had forgotten to update the readme

Update readme about scripts

---

kinto_attachment/__init__.py
kinto_attachment/tests/test_views_attachment.py
kinto_attachment/views.py

Add heartbeat entry for attachments backend (fixes #41)

---

CHANGELOG.rst
README.rst
kinto_attachment/tests/config/events.ini
kinto_attachment/tests/config/s3.ini
kinto_attachment/tests/test_views_attachment.py
kinto_attachment/views.py

Add setting to keep old files

---

README.rst
kinto_attachment/tests/__init__.py
kinto_attachment/tests/test_events.py
kinto_attachment/tests/test_views_attachment.py
kinto_attachment/views/__init__.py
kinto_attachment/views/services.py

based on top of #61 
@Natim r?

Optional randomize

---

scripts/upload.py
tox.ini

Allow unrandomized upload

---

README.rst

Fix README setting name for bucket name

---

kinto_attachment/tests/test_views_attachment.py
kinto_attachment/views/__init__.py

Do nothing in heartbeat if server is readonly (fixes #69)

---

README.rst
demo/README.rst

Update readthedocs link.

---

scripts/upload.py

kinto_client is not in the setup.py but the script depends on it nevertheless.

Port to kinto_client 5.0.0

---

CHANGELOG.rst
kinto_attachment/listeners.py
kinto_attachment/tests/__init__.py
kinto_attachment/tests/test_events.py
kinto_attachment/tests/test_plugin_setup.py
kinto_attachment/tests/test_views_attachment.py
kinto_attachment/utils.py
kinto_attachment/views/__init__.py
kinto_attachment/views/services.py

This updates kinto-attachment according to the changes made in https://github.com/Kinto/kinto/releases/tag/3.0.0.

update Cliquet references to kinto.core

---

CHANGELOG.rst
setup.py

**Step 1**
```
$ git co -b prepare-X.X
$ prerelease
$ vim docs/conf.py
$ git ci -a --amend
$ git push origin prepare-X.X
```
**Step 2**
```
$ git co master
$ git merge --no-ff prepare-X.X
$ release
$ postrelease
```
**Step 3**
@Natim r?

Preparing release 0.6.0

---

.travis.yml
Makefile
kinto_attachment/tests/config/functional.ini
tox.ini

Run functional tests on travis.

---

CHANGELOG.rst
kinto_attachment/tests/test_views_attachment.py
kinto_attachment/views/__init__.py

Fix crash when the file is not uploaded using attachment field name (fixes #57)

---

CHANGELOG.rst
kinto_attachment/views/services.py

Tested locally with demo, works fine, OPTIONS requests are fulfilled.
@Natim r?

Remove hard-coded CORS setup (fixes #59)

---

CHANGELOG.rst
kinto_attachment/utils.py

Fix call to Record resource with last kinto release. — Fixes #97

---

CHANGELOG.rst
kinto_attachment/tests/test_views_attachment.py
kinto_attachment/views/__init__.py

* Ref #74 
* Ref #100 
@Natim r?

Better message for 400 errors

---

CHANGELOG.rst
kinto_attachment/tests/test_views_attachment.py
kinto_attachment/views/__init__.py

Fix crash when submitted data is not valid JSON (fixes #104)

---

scripts/requirements.txt

Add scripts dependencies — Fixes #94

---

CHANGELOG.rst
kinto_attachment/__init__.py
kinto_attachment/tests/test_plugin_setup.py

Refs https://github.com/Kinto/kinto/issues/591
r? @tarekziade

Add kinto-attachment plugin version in the capability.

---

CHANGELOG.rst
kinto_attachment/__init__.py
kinto_attachment/tests/__init__.py
kinto_attachment/tests/test_events.py
kinto_attachment/tests/test_plugin_setup.py
kinto_attachment/tests/test_utils.py
kinto_attachment/tests/test_views_attachment.py
setup.py

Remove the public settings since the accurate URL is now in the capability.

---

CHANGELOG.rst
setup.py

Preparing release 1.0.0

---

CHANGELOG.rst
kinto_attachment/tests/test_views_attachment.py
kinto_attachment/utils.py
tox.ini

Add a cornice compatibility patch.

---

kinto_attachment/__init__.py
kinto_attachment/tests/test_plugin_setup.py
kinto_attachment/tests/test_views_attachment.py

Expose the gzipped default value in the capability.

---

CHANGELOG.rst
kinto_attachment/tests/test_views_attachment.py
kinto_attachment/utils.py

Fix invalid request when attaching a file on non UUID record id (fixes #122)

---

CHANGELOG.rst
kinto_attachment/utils.py

Set resource name before instantiating record.

---

scripts/download.py
scripts/requirements.txt
scripts/upload.py
tox.ini

- Upgrade to kinto-http
- Add a force option
- Don't fail everything if one file fails to upload

Upgrade upload script to handle update from filename and force update.

---

CHANGELOG.rst
kinto_attachment/listeners.py
kinto_attachment/tests/test_views_attachment.py
kinto_attachment/views/__init__.py

Do not delete attachment when record is deleted if keep_old_files setting is true (#137)

---

CHANGELOG.rst
README.rst
kinto_attachment/__init__.py
kinto_attachment/tests/__init__.py
kinto_attachment/tests/config/s3_per_resource.ini
kinto_attachment/tests/test_plugin_setup.py
kinto_attachment/tests/test_views_attachment.py
kinto_attachment/utils.py
kinto_attachment/views/__init__.py

Fixes #139
Less options, less headache, better life.

Simplify compression options (fixes #139)

---

README.rst

Fix README about hash hex digest (fixes #102)

---

CHANGELOG.rst
kinto_attachment/tests/test_utils.py
kinto_attachment/utils.py
kinto_attachment/views/__init__.py

Heartbeat now uses utils.save_file() for better detection of configuration or deployment errors (fixes #146)

---

.travis.yml
CHANGELOG.rst
Makefile
README.rst
dev-requirements.txt
kinto_attachment/listeners.py
kinto_attachment/tests/config/functional.ini
kinto_attachment/tests/test_views_attachment.py
kinto_attachment/utils.py
kinto_attachment/views.py
requirements.txt
scripts/create_account.py
scripts/delete.py
scripts/upload.py
tox.ini

Commit attachment deletion (fixes #149)

---

CHANGELOG.rst
kinto_attachment/utils.py

Requires https://github.com/danjac/pyramid_storage/pull/39 
@smarnach r?

Add missing content type when uploading to S3

---

README.rst

Fix #617: document release process

---

Makefile
kinto_attachment/tests/config/s3.ini
kinto_attachment/tests/config/s3_per_resource.ini
kinto_attachment/tests/test_views_attachment.py

5000 is used by AirDrop on MacOS :)

Switch moto from 5000 to 6000

---

.github/workflows/lint.yml
.github/workflows/test.yml
README.rst
tox.ini

Refs #692 
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

Get ready moving master into main
